services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html:z
    depends_on:
      - db

  db:
    image: mariadb:lts
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password # Cambia esto
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d:ro,z

  adminer:
    image: docker.io/library/adminer:latest
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  mariadb_data: